### ISSUE TITLE
Channel D (A-B) function is calculated incorrectly

### ISSUE THREAD

**Issue by dementianati** [pmos69/dso203_gcc#13]
Patch for Process.c to correct problem with (A-B) calculation.

The code confuses + and - signs, so the calculation offsets the display incorrectly.  The following diff to the Process.c file corrects this.

. # diff Process.c Process_corrected.c
.
. 37c37
. < s16 Posi_412, Posi_41, Posi_42, Posi_4_2, Posi_4F1, Posi_4F2, Posi_4F3, Posi_4F4;
. ---
. > s16 Posi_412, Posi_41_2, Posi_41, Posi_42, Posi_4_2, Posi_4F1, Posi_4F2, Posi_4F3, Posi_4F4;
. 326a327
. >   Posi_41_2 = _4_posi - _1_posi + _2_posi;
. 539c540
. <     Tmp = Posi_412 + Va - Vb;
. ---
. >     Tmp = Posi_41_2 + Va - Vb;

**Comment by pmos69** [comment]
Thank you, and sorry for the delay.
Not really been able to do any further work on this due to lack of time.
Patch commited.
