### ISSUE TITLE
Signal Generator Frequency

### ISSUE THREAD

**Issue by james-martinez** [pmos69/dso203_gcc#9]
The signal generator is off. Max frequency is 10khz on square wave. PWM can go to higher frequency but the selections are screwed up.

**Comment by pmos69** [comment]
Don't have time to look into it this week, but are you using the right SYS?
The APP is supposed to be used with SYS 1.50 1.6 from Marco Sinatti. Some changes in Marco's SYS affect the frequency generator.

**Comment by james-martinez** [comment]
Thanks
